// Mocks generated by Mockito 5.3.2 from annotations
// in kotobaten/models/slices/user/user_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:kotobaten/models/slices/user/user.dart' as _i4;
import 'package:kotobaten/models/slices/user/user_core.dart' as _i6;
import 'package:kotobaten/models/slices/user/user_goals.dart' as _i5;
import 'package:kotobaten/models/slices/user/user_repository.dart' as _i3;
import 'package:kotobaten/models/slices/user/user_service.dart' as _i8;
import 'package:kotobaten/models/slices/user/user_statistics.dart' as _i7;
import 'package:kotobaten/services/kotobaten_api.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKotobatenApiService_0 extends _i1.SmartFake
    implements _i2.KotobatenApiService {
  _FakeKotobatenApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRepository_1 extends _i1.SmartFake
    implements _i3.UserRepository {
  _FakeUserRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserInitialized_2 extends _i1.SmartFake
    implements _i4.UserInitialized {
  _FakeUserInitialized_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserGoals_3 extends _i1.SmartFake implements _i5.UserGoals {
  _FakeUserGoals_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCoreInitialized_4 extends _i1.SmartFake
    implements _i6.UserCoreInitialized {
  _FakeUserCoreInitialized_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserStatistics_5 extends _i1.SmartFake
    implements _i7.UserStatistics {
  _FakeUserStatistics_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i8.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KotobatenApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeKotobatenApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.KotobatenApiService);
  @override
  _i3.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_1(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i3.UserRepository);
  @override
  _i9.Future<dynamic> refreshUser({bool? updateRetentionBackstop = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshUser,
          [],
          {#updateRetentionBackstop: updateRetentionBackstop},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> completeOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #completeOnboarding,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);
  @override
  _i4.UserInitialized setUser(_i4.UserInitialized? user) => (super.noSuchMethod(
        Invocation.method(
          #setUser,
          [user],
        ),
        returnValue: _FakeUserInitialized_2(
          this,
          Invocation.method(
            #setUser,
            [user],
          ),
        ),
      ) as _i4.UserInitialized);
  @override
  _i9.Future<_i5.UserGoals> updateGoals(_i5.UserGoals? goals) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGoals,
          [goals],
        ),
        returnValue: _i9.Future<_i5.UserGoals>.value(_FakeUserGoals_3(
          this,
          Invocation.method(
            #updateGoals,
            [goals],
          ),
        )),
      ) as _i9.Future<_i5.UserGoals>);
  @override
  _i9.Future<_i6.UserCoreInitialized> updateRetentionBackstopMaxThreshold(
          int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRetentionBackstopMaxThreshold,
          [number],
        ),
        returnValue: _i9.Future<_i6.UserCoreInitialized>.value(
            _FakeUserCoreInitialized_4(
          this,
          Invocation.method(
            #updateRetentionBackstopMaxThreshold,
            [number],
          ),
        )),
      ) as _i9.Future<_i6.UserCoreInitialized>);
  @override
  _i7.UserStatistics updateStatistics(_i7.UserStatistics? stats) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatistics,
          [stats],
        ),
        returnValue: _FakeUserStatistics_5(
          this,
          Invocation.method(
            #updateStatistics,
            [stats],
          ),
        ),
      ) as _i7.UserStatistics);
}
