name: kotobaten
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.0+0

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0
  freezed_annotation: ^1.1.0
  build_runner: ^2.1.5
  tuple: ^2.0.0
  path: ^1.8.0
  shared_preferences: ^2.0.8
  json_annotation: ^4.3.0
  pull_to_refresh: ^2.0.0
  audioplayers: ^0.20.1
  url_launcher: ^6.0.17
  collection: ^1.15.0
  rxdart: ^0.27.3
  visibility_detector: ^0.2.2
  flutter_local_notifications: ^9.3.1
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  bitsdojo_window: ^0.1.2
  package_info_plus: ^1.4.2

  http: ^0.13.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  

dev_dependencies:
  freezed: ^1.1.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.1
  mockito: ^5.0.16
  lints: ^1.0.1
  msix: ^3.3.2
  flutter_launcher_icons: ^0.9.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/square_gray.png
    - assets/logos/logo_wide_white.png
    - assets/logos/logo_wide_color.png
    - assets/onboarding/practice_onboarding_0.png
    - assets/onboarding/practice_onboarding_1.png
    - assets/onboarding/practice_onboarding_2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSerifJP
      fonts:
        - asset: assets/fonts/NotoSerifJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSerifJP-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSerifJP-Black.otf
          weight: 900

msix_config:
  display_name: "Kotobaten: Expand your Japanese"
  publisher_display_name: Jan Kratochvil
  identity_name: 	7003JanKratochvil.KotobatenExpandyourvocabularyund
  msix_version: 0.0.0.0
  logo_path: assets/logos/logo_windows.png
  capabilities: internetClient
  publisher: CN=6DEA31B6-2495-4821-93B5-2876078C935E
  store: true

flutter_icons:
  android: false
  ios: true
  image_path: "assets/logos/logo_ios.png"