// Mocks generated by Mockito 5.0.16 from annotations
// in kotobaten/services/analytics_service.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:kotobaten/models/app_configuration.dart' as _i2;
import 'package:kotobaten/models/slices/user/user.dart' as _i6;
import 'package:kotobaten/services/analytics_events.dart' as _i7;
import 'package:kotobaten/services/analytics_service.dart' as _i3;
import 'package:mixpanel_flutter/mixpanel_flutter.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAppConfiguration_0 extends _i1.Fake implements _i2.AppConfiguration {
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i3.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set mixpanel(_i4.Mixpanel? _mixpanel) =>
      super.noSuchMethod(Invocation.setter(#mixpanel, _mixpanel),
          returnValueForMissingStub: null);
  @override
  _i2.AppConfiguration get configuration =>
      (super.noSuchMethod(Invocation.getter(#configuration),
          returnValue: _FakeAppConfiguration_0()) as _i2.AppConfiguration);
  @override
  _i5.Future<dynamic> initialize() =>
      (super.noSuchMethod(Invocation.method(#initialize, []),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  void setUser(_i6.User? user) =>
      super.noSuchMethod(Invocation.method(#setUser, [user]),
          returnValueForMissingStub: null);
  @override
  void track(_i7.AnalyticsEvents? event) =>
      super.noSuchMethod(Invocation.method(#track, [event]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
