name: Common enviornment setup


on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

jobs:
  common_environment_setup:
    name: Common environment setup
    runs-on: {{ inputs.runs-on }}
    steps:
    - name: Checkout from git
      uses: actions/checkout@v2.3.1

    - name: Gets Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'
        channel: 'stable'

    - name: Downloads packages
      run: flutter pub get