name: Web - Integrity Checks
on:
  pull_request

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.1
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.0.2'
            channel: 'stable'
        - run: flutter pub get
        - run: flutter build web
        - run: flutter test