name: Deploy to Web
on:
  push:
    branches:
      - main

jobs:
    web:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout from git
          uses: actions/checkout@v2.3.1

        - name: Gets Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.24.3'
            channel: 'stable'

        - name: Downloads packages
          run: flutter pub get

        - name: Get timestamp
          id: get_timestamp
          run: echo "::set-output name=TIMESTAMP::$(date +'%Y%m%d%H%M')"


        - name: Embeds version into pubspec.yaml
          uses: jacobtomlinson/gha-find-replace@v2
          with:
            find: "0.0.0+0"
            replace: 0.0.0+${{ steps.get_timestamp.outputs.TIMESTAMP }}
            regex: false
            include: "pubspec.yaml"

        - uses: actions/upload-artifact@v3
          with:
            name: versioned-pubspec-web-android
            path: pubspec.yaml

        - name: Builds web
          run: flutter build web --source-maps

        - name: Pushes web to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: build/web # The folder the action should deploy. 

        # There is some brokenness regarding hashes, need to fix it
        # - name: Upload Source to Sentry
        #   run: flutter packages pub run sentry_dart_plugin --ignore-missing
        #   env:
        #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
